export const MOCK_DATA = [
  {
    id: 1,
    name: 'Liliane',
    surname: 'Wankling',
    email: 'lwankling0@freewebs.com',
    birthdate: '09/12/1969',
    position: 'Senior',
    altPos: '',
  },
  {
    id: 2,
    name: 'Si',
    surname: 'Tremayne',
    email: 'stremayne1@stanford.edu',
    birthdate: '02/10/1955',
    position: 'Junior',
    altPos: '',
  },
  {
    id: 3,
    name: 'Katuscha',
    surname: 'Grabham',
    email: 'kgrabham2@dailymail.co.uk',
    birthdate: '26/11/1954',
    position: 'Senior',
    altPos: '',
  },
  {
    id: 4,
    name: 'Karissa',
    surname: 'Bonwell',
    email: 'kbonwell3@usa.gov',
    birthdate: '08/05/2004',
    position: 'Senior',
    altPos: '',
  },
  {
    id: 5,
    name: 'Zitella',
    surname: 'Bigg',
    email: null,
    birthdate: '24/12/1991',
    position: 'Other',
    altPos: '',
  },
  {
    id: 6,
    name: 'Jasper',
    surname: 'Trehearne',
    email: 'jtrehearne5@mlb.com',
    birthdate: '11/02/1957',
    position: 'Junior',
    altPos: '',
  },
  {
    id: 7,
    name: 'Krisha',
    surname: 'Ranyard',
    email: null,
    birthdate: '03/01/1964',
    position: 'Junior',
    altPos: '',
  },
  {
    id: 8,
    name: 'Farra',
    surname: 'Liggons',
    email: 'fliggons7@hatena.ne.jp',
    birthdate: '21/02/1962',
    position: 'Senior',
    altPos: '',
  },
  {
    id: 9,
    name: 'Richmound',
    surname: 'Headech',
    email: 'rheadech8@symantec.com',
    birthdate: '26/12/1957',
    position: 'Junior',
    altPos: '',
  },
  {
    id: 10,
    name: 'Christi',
    surname: 'Southernwood',
    email: 'csouthernwood9@youtu.be',
    birthdate: '02/01/1972',
    position: 'Senior',
    altPos: '',
  },
  {
    id: 11,
    name: 'Vittoria',
    surname: 'Norsister',
    email: 'vnorsistera@macromedia.com',
    birthdate: '04/09/1980',
    position: 'Senior',
    altPos: '',
  },
  {
    id: 12,
    name: 'Delmer',
    surname: 'Bartlomieczak',
    email: 'dbartlomieczakb@imageshack.us',
    birthdate: '30/12/1966',
    position: 'Other',
    altPos: '',
  },
  {
    id: 13,
    name: 'Ulick',
    surname: 'Storre',
    email: 'ustorrec@soup.io',
    birthdate: '19/07/1989',
    position: 'Junior',
    altPos: '',
  },
  {
    id: 14,
    name: 'Hilary',
    surname: 'Mullaly',
    email: 'hmullalyd@behance.net',
    birthdate: '24/05/1984',
    position: 'Junior',
    altPos: '',
  },
  {
    id: 15,
    name: 'Margaretha',
    surname: 'Finch',
    email: 'mfinche@google.co.uk',
    birthdate: '06/11/1986',
    position: 'Senior',
    altPos: '',
  },
  {
    id: 16,
    name: 'Annemarie',
    surname: 'Aicheson',
    email: 'aaichesonf@i2i.jp',
    birthdate: '08/09/1952',
    position: 'Other',
    altPos: '',
  },
  {
    id: 17,
    name: 'Seth',
    surname: 'Cattanach',
    email: null,
    birthdate: '14/04/1965',
    position: 'Junior',
    altPos: '',
  },
  {
    id: 18,
    name: 'Marybelle',
    surname: 'Plante',
    email: 'mplanteh@amazonaws.com',
    birthdate: '04/03/1988',
    position: 'Other',
    altPos: '',
  },
  {
    id: 19,
    name: 'Alexander',
    surname: 'Coltherd',
    email: 'acoltherdi@senate.gov',
    birthdate: '04/06/2000',
    position: 'Junior',
    altPos: '',
  },
  {
    id: 20,
    name: 'Devy',
    surname: 'Foucar',
    email: 'dfoucarj@hp.com',
    birthdate: '20/01/1978',
    position: 'Junior',
    altPos: '',
  },
];
